name: CI
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # Skip intermediate builds: all builds except for builds on the `master` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read

jobs:
  finalize:
    timeout-minutes: 10
    needs: [test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo test: ${{ needs.test.result }}
      - run: exit 1
        if: (needs.test.result != 'success')

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    env:
      JULIA_PKG_SERVER: "pkg.julialang.org"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: julia-actions/install-juliaup@1da6847c869cd68e3a32b8f52fe8f005b8cd5ece # v2.2.1
        with:
          channel: "release"

      - uses: julia-actions/julia-buildpkg@e3eb439fad4f9aba7da2667e7510e4a46ebc46e1 # v1.7.0

      - uses: julia-actions/julia-runtest@678da69444cd5f13d7e674a90cb4f534639a14f9 # v1.11.2
